package com.techdome.saralCRM.Pages;

public class Locator_Constant {
    protected static final String EMAIL_FIELD = "//input[@id ='email']";
    protected static final String PASSWORD_FIElD = "//input[@id ='password']";
    protected static final String LOGIN_BUTTON = "//button[text() ='Login']";
    protected static final String TO_VALIDATE_EMAIL = "//span[@class='profile-email']";
    protected static final String FORGOT_PASSWORD = "//a[text() ='Forgot password?']";
    protected static final String EMAIL_ADDRESS = "//input[@type ='email']";
    protected static final String BTN_RESETPASSWORD = "//button[text() = 'Reset Password']";
    protected static final String RESET_PASSWORD_MSG = "//h3[text()='Reset Password Link Sent']";
    protected static final String INVALID_EMAIL = "//div[@class='text-red-500 text-xs mt-1 leading-tight']";
    protected static final String INVALID_PASSWORD = "//div[@class='text-red-500 text-xs mt-1']";
    protected static final String NOT_REGISTERED_EMAIL = "//div[@class='text-red-500 text-xs mt-1']";
    protected static final String NOT_REGISTERED_EMAIL_FORGOT_PASSWORD = "//div[@class='text-red-500 text-xs mt-1 leading-tight']";
    protected static final String EMPTY_EMAIL = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[1]";
    protected static final String EMPTY_PASSWORD = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[1]";
    protected static final String BTN_BACK_TO_LOGIN = "//button[text() ='Back to Login']";
    protected static final String WITHOUT_PASSWORD = "//div[@class='text-red-500 text-xs mt-1 leading-tight']";
    protected static final String BTN_BACKTOLOGIN = "//button[text()='Back to Login']";
    protected static final String BTN_FILTER = "//i[@class='bi bi-funnel']";
    protected static final String CKBOX_UPTO25L = "(//input[@type='checkbox'])[1]";
    protected static final String CKBOX_UPTO2CR = "(//input[@type='checkbox'])[2]";
    protected static final String CKBOX_UPTO10CR = "(//input[@type='checkbox'])[3]";
    protected static final String CKBOX_ABOVE10CR = "(//input[@type='checkbox'])[4]";
    protected static final String BTN_APPLYFILTER = "//button[text()='Apply Filters']";
    protected static final String BTN_COLUMNS = "//button[text()='Columns']";
    protected static final String BTN_ADDLEAD = "//i[@class = 'bi bi-plus-lg']";
    protected static final String BTN_LEAD = "//button[text() ='Add Lead']";
    protected static final String EMPTY_NAME = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[1]";
    protected static final String EMPTY_NUMBER = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[2]";
    protected static final String EMT_ID = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[3]";
    protected static final String TEXT_NAME = "//input[@id='full_name']";
    protected static final String TEXT_NUMBER = "//input[@id='phone_number']";
    protected static final String TEXT_ID = "//input[@id='email']";
    protected static final String PARTIAL_NAME_MSG = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[1]";
    protected static final String PARTIAL_NUMBER_MSG = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[2]";
    protected static final String PARTIAL_ID_MSG = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[3]";
    protected static final String VALIDATION_MESSAGE = "//div[@class='text-red-500 text-xs mt-1 leading-tight']";
    protected static final String BTN_CANCEL = "//button[text()='Cancel']";
    protected static final String NOTIFICATION_TOGGLE = "//*[text()='A user with this phone number already exists']";
    protected static final String SEARCH_BAR = "//input[@placeholder='Search by Name, Loan Type, Source, Employment']";
    protected static final String SEARCH_ICON = "//i[@class='bi bi-search text-white']";
    protected static final String USER_NUMBER = "(//div[@class='text-gray-600 text-sm'])[1]";
    protected static final String SEARCH_USER = "//div[@class='text-gray-600 text-sm']";
    protected static final String LOAN_AMOUNT_TOGGLE = "//span[text()='Loan Amount']//..//div";
    protected static final String EMPLOYMENT_TYPE_TOGGLE = "//span[text()='Employment Type']//..//div";
    protected static final String LOAN_TYPE_TOGGLE = "//span[text()='Loan Type']//..//div";
    protected static final String LEAD_SOURCE_TOGGLE = "//span[text()='Lead Source']//..//div";
    protected static final String CIBIL_SCORE_TOGGLE = "//span[text()='CIBIL Score']//..//div";
    protected static final String ADDED_ON_TOGGLE = "//span[text()='Added On']//..//div";
    protected static final String COLUMN_SAVE_BTN = "//button[text()='Save']";
    protected static final String COLUMN_CANCEL_BTN = "//button[text()='Cancel']";
    protected static final String FILTER_EMPLOYMENT_TYPE = "//span[text() = 'Employment Type']";
    protected static final String CK_SALARY = "(//input[@type ='checkbox'])[1]";
    protected static final String CK_BUSINESS = "(//input[@type ='checkbox'])[2]";
    protected static final String FILTER_CIBIL_SCORE ="//span[text()='CIBIL Score']";
    protected static final String CK_UP_TO_500 = "(//input[@type ='checkbox'])[1]";
    protected static final String CK_UP_TO_700 = "(//input[@type ='checkbox'])[2]";
    protected static final String CK_UP_TO_850 = "(//input[@type ='checkbox'])[3]";
    protected static final String BTN_CLEAR_ALL = "//div[text()='Clear all']";
    protected static final String BTN_FILTER_SOURCE = "//span[text()='Source']";
    protected static final String CK_FACEBOOK = "(//input[@type ='checkbox'])[1]";
    protected static final String CK_WEBSITE = "(//input[@type ='checkbox'])[2]";
    protected static final String CK_INSTAGRAM = "(//input[@type ='checkbox'])[3]";
    protected static final String CK_WHATSAPP = "(//input[@type ='checkbox'])[4]";
    protected static final String CK_CRM = "(//input[@type ='checkbox'])[5]";
    protected static final String LOAN_AMOUNT_VALUE = "//td[@class='py-3 px-4'][2]";
    protected static final String EMPLOYMENT_TYPE_VALUE = "//td[@class='py-3 px-4'][3]";
    protected static final String SOURCE_VALUE = "//td[@class='py-3 px-4'][5]";
    protected static final String CIVIL_VALUE = "//td[@class='py-3 px-4'][6]";
    protected static final String SEARCH_LOAN_TYPE = "//td[@class='py-3 px-4'][4]";
    protected static final String APPLY_FILTERS_NOTIFICATION = "//div[@class='Toastify__toast Toastify__toast-theme--light Toastify__toast--success']";
    protected static final String BTN_EYE_ICON = "//i[@class ='bi bi-eye text-secondary']";
    protected static final String BTN_EDIT_PROFILE = "//button[text()='Edit Profile']";
    protected static final String USER_NAME_TEXT = "//p[@class='text-xl font-semibold']";
    protected static final String EP_USER_NAME = "//input[@placeholder='Enter your name']";
    protected static final String EP_USER_ID = "//input[@placeholder = 'Enter your Email ID']";
    protected static final String BTN_UPDATE_LEAD = "//button[text()='Update Lead']";
    protected static final String EP_INVALID_NAME = "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[1]";
    protected static final String EP_INVALID_ID =   "(//div[@class='text-red-500 text-xs mt-1 leading-tight'])[2]";
    protected static final String BTN_NOTES = "//span[text()='Notes']";
    protected static final String BTN_ADD_NOTES = "//button[text()='Add Note']";
    protected static final String TXTBOX_ADD_NOTE = "//div[@class = 'ql-editor ql-blank']";
    protected static final String BTN_ADDNOTE = "(//button[text()='Add Note'])[2]";
    protected static final String TXT_CONTENT = "(//div[@class = 'text-gray-500 text-sm'])[1]";
    protected static final String CANCEL_ADDED_NOTES = "//button[text()='Cancel']";
    protected static final String BTN_DOCUMENT = "//span[text()='Documents']";
    protected static final String BTN_UPLOAD_DOCUMENT = "//button[text()='Upload Document']";
    protected static final String EMPTY_DOC_VALIDATION_MSG = "//p[@class='text-red-600 text-sm mt-1']";
    protected static final String BTN_IMPORT = "//button[text()='Import']";
    protected static final String DOCUMENT_DROPDOWN = "//span[text()='Select the kind of document']";
    protected static final String CHOOSE_FILE = "//button[text() = 'Choose file']";
    protected static final String ALL_DROPDOWN_ELEMENTS = "//div[@class='fixed bg-white border border-[#DEE2E6] rounded-md shadow-lg max-h-33 overflow-y-auto z-[9999]']/div";
    protected static final String MENU = "(//i[@class='bi bi-three-dots-vertical cursor-pointer'])[1]";
    protected static final String QUICK_OPTIONS_DROPDOWN = "//div[@class='absolute right-0 mt-2 w-40 border border-gray-300 bg-white rounded-md z-10']";
    protected static final String BTN_DELETE = "//li[text()='Delete']";
    protected static final String BTN_RENAME = "//li[text()='Rename']";
    protected static final String TXT_DOCUMENT_NAME = "//input[@type ='text']";
    protected static final String BTN_SAVE_RENAME = "//button[text() = 'Save']";
    protected static final String BTN_CANCEL_RENAME = "//button[text() = 'Cancel']";
    protected static final String RENAMED_NAME = "//td[@class='!p-2 flex-1 items-center']";
    protected static final String BTN_DELETE_OPTION = "//button[text()='Delete']";
    protected static final String BTN_CANCEL_DELETE = "//button[text()='Cancel']";
    protected static final String COLUMN_HEADING = "//thead[@class='sticky top-0 bg-success text-white z-10']";
    protected static final String RESET_TO_DEFAULT = "//div[text()='Reset to Default']";



}
